apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  storageClass:
    name: production-storage-class
  authentication:
    type: digest
    jaasConfig:
      secretRef: credential
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  dataVolumeCapacity: 10Gi
  storageClass:
    name: production-storage-class  
  configOverrides:
    jvm:
      - "-Djavax.net.ssl.trustStore=/mnt/jvmtruststore/truststore.jks"
      - "-Djavax.net.ssl.trustStorePassword=mystorepassword"
  mountedVolumes:
    volumes:
      - name: customtruststore
        secret:
          secretName: mycustomtruststore
    volumeMounts:
      - name: customtruststore
        mountPath: /mnt/jvmtruststore      
  listeners:
    external:
      authentication:
        type: oauth
        jaasConfig:
          secretRef: oauth-jass
        oauthSettings:
          tokenEndpointUri: https://keycloak.confluent.svc.cluster.local:8443/realms/sso_test/protocol/openid-connect/token
          expectedIssuer: https://keycloak.confluent.svc.cluster.local:8443/realms/sso_test
          jwksEndpointUri: https://keycloak.confluent.svc.cluster.local:8443/realms/sso_test/protocol/openid-connect/certs
          subClaimName: client_id
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181
      authentication:
        type: digest
        jaasConfig:
          secretRef: credential
---